apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: krishapp-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/krishchadha/remoteapi'
    targetRevision: dev
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
