name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Docker Image
        run: |
          docker build -t krishapp .
          docker tag krishapp:latest ${{ secrets.ECR_REPOSITORY_URI }}:latest

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}

      - name: Push to ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest

      # - name: Update Kubernetes Deployment
      #   run: |
      #     kubectl set image deployment/krishapp krishapp=${{ secrets.ECR_REPOSITORY_URI }}:latest -n staging
